// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspcore.Data;

#nullable disable

namespace aspcore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221203092055_conf approve")]
    partial class confapprove
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aspcore.Models.Conference", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<bool>("Acknowledge")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amounts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attach1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attach2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degrees")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GlobalCollege")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PriviteCollege")
                        .HasColumnType("bit");

                    b.Property<bool>("PublicCollege")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopusLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploaderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("aspcore.Models.ConferencePaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AcknowledgeMoney")
                        .HasColumnType("int");

                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConferenceMoney")
                        .HasColumnType("int");

                    b.Property<int>("ConferenceTotalAmount")
                        .HasColumnType("int");

                    b.Property<int?>("externalResearcherMoney")
                        .HasColumnType("int");

                    b.Property<int?>("femaleM")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConferencePaymentLog");
                });

            modelBuilder.Entity("aspcore.Models.ConferenceResearch", b =>
                {
                    b.Property<long>("ConferenceId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResearcherId")
                        .HasColumnType("bigint");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FirstPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ResearcherArName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherDeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherEnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ResearcherMoney")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConferenceId", "ResearcherId");

                    b.ToTable("ConferenceResearches");
                });

            modelBuilder.Entity("aspcore.Models.DepTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("depname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepTable");
                });

            modelBuilder.Entity("aspcore.Models.PaymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long?>("ExtResrchMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("ImpactFacterMoney")
                        .HasColumnType("bigint");

                    b.Property<long>("ResearchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SDGMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("ThanksOFcollMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("citationM")
                        .HasColumnType("bigint");

                    b.Property<long?>("clarivateMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("femaleM")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("openAccessMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("other")
                        .HasColumnType("bigint");

                    b.Property<long?>("publishedMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("quartileMoney")
                        .HasColumnType("bigint");

                    b.Property<long?>("scopusHumanDepartmentMoney")
                        .HasColumnType("bigint");

                    b.Property<long>("total")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PaymentLog");
                });

            modelBuilder.Entity("aspcore.Models.PaymentSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CitationFrom11To15")
                        .HasColumnType("int");

                    b.Property<int>("CitationFrom16To20")
                        .HasColumnType("int");

                    b.Property<int>("CitationFrom1To3")
                        .HasColumnType("int");

                    b.Property<int>("CitationFrom4To7")
                        .HasColumnType("int");

                    b.Property<int>("CitationFrom8To10")
                        .HasColumnType("int");

                    b.Property<int>("CitationLargerThen20")
                        .HasColumnType("int");

                    b.Property<int>("ClarivateOnlly")
                        .HasColumnType("int");

                    b.Property<long>("ConferenceFirst")
                        .HasColumnType("bigint");

                    b.Property<long>("ConferenceGlobalResearcher")
                        .HasColumnType("bigint");

                    b.Property<long>("ConferenceLocalResearcher")
                        .HasColumnType("bigint");

                    b.Property<long>("ConferenceSecend")
                        .HasColumnType("bigint");

                    b.Property<int>("Female")
                        .HasColumnType("int");

                    b.Property<long>("Grant")
                        .HasColumnType("bigint");

                    b.Property<int>("ImpactFacterFrom1To2")
                        .HasColumnType("int");

                    b.Property<int>("ImpactFacterFrom2To3")
                        .HasColumnType("int");

                    b.Property<int>("ImpactFacterFrom3To4")
                        .HasColumnType("int");

                    b.Property<int>("ImpactFacterFrom4To5")
                        .HasColumnType("int");

                    b.Property<int>("ImpactFacterLargerThan5")
                        .HasColumnType("int");

                    b.Property<long>("MainR")
                        .HasColumnType("bigint");

                    b.Property<int>("Q1First")
                        .HasColumnType("int");

                    b.Property<int>("Q1Second")
                        .HasColumnType("int");

                    b.Property<int>("Q2First")
                        .HasColumnType("int");

                    b.Property<int>("Q2Second")
                        .HasColumnType("int");

                    b.Property<int>("Q3First")
                        .HasColumnType("int");

                    b.Property<int>("Q3Second")
                        .HasColumnType("int");

                    b.Property<int>("Q4First")
                        .HasColumnType("int");

                    b.Property<int>("Q4Second")
                        .HasColumnType("int");

                    b.Property<int>("SDG")
                        .HasColumnType("int");

                    b.Property<int>("ScopusHumanDepartment")
                        .HasColumnType("int");

                    b.Property<int>("ThanksForMustaqbal")
                        .HasColumnType("int");

                    b.Property<int>("conferenceAcknowledgment")
                        .HasColumnType("int");

                    b.Property<int>("externalGloabalResearcher")
                        .HasColumnType("int");

                    b.Property<int>("externalLocalResearcher")
                        .HasColumnType("int");

                    b.Property<int>("inClarivate")
                        .HasColumnType("int");

                    b.Property<int>("openAccess")
                        .HasColumnType("int");

                    b.Property<int>("publisher")
                        .HasColumnType("int");

                    b.Property<long>("responsible")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("paymentSettings");
                });

            modelBuilder.Entity("aspcore.Models.ResearcherAndCorresponding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("uploaderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResearcherAndCorresponding");
                });

            modelBuilder.Entity("aspcore.Models.ResearcherTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<int?>("BatchNo")
                        .HasColumnType("int");

                    b.Property<int?>("CorrPaidAmount")
                        .HasColumnType("int");

                    b.Property<string>("CorrPaidArder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CorrPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrReceivingSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrRecipientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondingAuthors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalResearcher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JournalQuarter")
                        .HasColumnType("int");

                    b.Property<string>("JournalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientMoneyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchAbstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearchTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResearcherPosition")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TotalAmountDesFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalAmountReceived")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploaderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResearcherTable");
                });

            modelBuilder.Entity("aspcore.Models.ResearchMUS", b =>
                {
                    b.Property<int>("Form_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Form_No"), 1L, 1);

                    b.Property<string>("Amounts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degrees")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExtResrch")
                        .HasColumnType("bit");

                    b.Property<string>("ExtResrchDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExtResrch_Globl")
                        .HasColumnType("bit");

                    b.Property<bool>("ExtResrch_Local")
                        .HasColumnType("bit");

                    b.Property<string>("ISSNorEISSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<double?>("ImpactFacter")
                        .HasColumnType("float");

                    b.Property<string>("JournalCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Names")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OtherResearch")
                        .HasColumnType("int");

                    b.Property<string>("QRimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCOPUS_link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDGtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ThanksOFcoll")
                        .HasColumnType("bit");

                    b.Property<string>("appledPaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attachedFile1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attachedFile2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attachedFile3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attachedFile4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("checkState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("citeScore")
                        .HasColumnType("float");

                    b.Property<bool>("clarivate")
                        .HasColumnType("bit");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("externalResearcher")
                        .HasColumnType("bit");

                    b.Property<string>("fileRes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("journaltitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("journalurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("openAccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pubDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("published")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisherEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quartile")
                        .HasColumnType("int");

                    b.Property<int?>("rankOutOf")
                        .HasColumnType("int");

                    b.Property<bool?>("scopas")
                        .HasColumnType("bit");

                    b.Property<bool?>("scopusHumanDepartment")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("totalMoney")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("viewlvl")
                        .HasColumnType("int");

                    b.HasKey("Form_No");

                    b.ToTable("ResearchMUS");
                });

            modelBuilder.Entity("aspcore.Models.RR2tabel", b =>
                {
                    b.Property<long>("ResearchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResearcherId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FirstPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ResearcherArName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherDeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherDept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherEnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResearcherGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResearcherLvl")
                        .HasColumnType("int");

                    b.Property<long?>("ResearcherMoney")
                        .HasColumnType("bigint");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResearchId", "ResearcherId");

                    b.ToTable("RR2tabel");
                });

            modelBuilder.Entity("aspcore.Models.TableCV", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("depid")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TableCV");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("aspcore.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
